version: "3.7"

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_USER=1
      - MYSQL_PASSWORD=1
      - MYSQL_DATABASE=rsse
      - MYSQL_ROOT_PASSWORD=1
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql

  rsse:
    build: .
    container_name: rsse
    restart: always
    ports:
      - 5000:5000

volumes:
  mysql-volume:
